language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install: composer self-update

install:
  - cd core
  - composer install --prefer-source --no-interaction
  - composer require squizlabs/php_codesniffer
  - mkdir -p ~/build
  - git clone --branch hubzero-cms-2.1 https://github.com/hubzero/standards ~/build/standards
  - cd ../ && FILES=$(git log --pretty=format\:'' --name-only --since="yesterday" | sort | uniq | tr '\r\n' ' ')

script:
  - core/vendor/bin/phpcs -np --standard=~/build/standards/Php/ruleset.xml --ignore=*/test/*,*/assets/*,*/views/*,*/tmpl/* $FILES
